In [32]:
import nltk
from nltk.corpus import stopwords
import pandas as pd
import numpy as np


In [33]:
data = pd.read_csv(r"C:\Users\SANKET\OneDrive\Desktop\180 Projects\Email Spam\email spam 2.csv")
data

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [37]:
data.drop_duplicates(inplace= True)
data

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [38]:
data.isnull().sum()

text    0
spam    0
dtype: int64

In [39]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SANKET\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [56]:
import string

In [57]:
def process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)

    clean = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    return clean
# to show the tokenization
data['text'].head().apply(process)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [58]:
from sklearn.feature_extraction.text import CountVectorizer
message = CountVectorizer(analyzer=process).fit_transform(data['text'])

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(message, data['spam'], train_size=0.8, test_size=0.2, random_state=0)
message.shape

(5695, 37229)

In [64]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train, y_train)
model.predict(X_valid)
y_train.values

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [63]:
model.score(X_train, y_train)

0.9971466198419666

In [67]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
pred = model.predict(X_train)
classification_report(y_train, pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00      3457\n           1       0.99      1.00      0.99      1099\n\n    accuracy                           1.00      4556\n   macro avg       0.99      1.00      1.00      4556\nweighted avg       1.00      1.00      1.00      4556\n'

In [68]:
print('Confusion Matrix : \n', confusion_matrix(y_train, pred))

Confusion Matrix : 
 [[3445   12]
 [   1 1098]]


In [70]:
print('accuracy score : \n', accuracy_score(pred, y_train))

accuracy score : 
 0.9971466198419666


In [71]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
pred2 = model.predict(X_valid)
classification_report(y_valid, pred2)

print('Confusion Matrix : \n', confusion_matrix(y_valid, pred2))

print('accuracy score : \n', accuracy_score(pred2, y_valid))

Confusion Matrix : 
 [[862   8]
 [  1 268]]
accuracy score : 
 0.9920983318700615
